In [2]:
import numpy as np 
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('../data/Bengaluru_House_Data.csv')

In [4]:
df.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [5]:
df.shape

(13320, 9)

In [6]:
df.sample(5)

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
6113,Super built-up Area,Ready To Move,Gollahalli,3 BHK,MJlese,1570,3.0,2.0,78.00
2273,Super built-up Area,Ready To Move,Sarjapur Road,3 BHK,Ceiti I,1845,4.0,1.0,110.00
6939,Built-up Area,Ready To Move,Doddakammanahalli,3 BHK,NaN,1542,3.0,2.0,98.00
1081,Super built-up Area,17-Oct,Banashankari,3 BHK,NaN,1470,2.0,1.0,88.64
3495,Plot Area,Ready To Move,Thanisandra,1 Bedroom,NaN,1380,1.0,1.0,62.10

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  str
 1   availability  13320 non-null  str
 2   location      13319 non-null  str
 3   size          13304 non-null  str
 4   society       7818 non-null   str
 5   total_sqft    13320 non-null  str
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), str(6)
memory usage: 1.6 MB

In [8]:
df.isnull().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [9]:
df.describe()

               bath       balcony         price
count  13247.000000  12711.000000  13320.000000
mean       2.692610      1.584376    112.565627
std        1.341458      0.817263    148.971674
min        1.000000      0.000000      8.000000
25%        2.000000      1.000000     50.000000
50%        2.000000      2.000000     72.000000
75%        3.000000      2.000000    120.000000
max       40.000000      3.000000   3600.000000

In [10]:
df.duplicated().sum()

np.int64(529)

In [11]:
df.drop_duplicates()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...,...
13314,Super built-up Area,Ready To Move,Green Glen Layout,3 BHK,SoosePr,1715,3.0,3.0,112.00
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00

In [12]:
df.rename(columns={"price": "price(in lakhs)", "bath": "bathrooms"}, inplace=True)

In [13]:
df.sample(5)

,area_type,availability,location,size,society,total_sqft,bathrooms,balcony,price(in lakhs)
9763,Super built-up Area,Ready To Move,Ganga Nagar,2 BHK,NaN,998,2.0,2.0,65.0
5004,Super built-up Area,Ready To Move,Kaggadasapura,2 BHK,WishiVa,1010,2.0,2.0,55.0
4730,Super built-up Area,18-Aug,Hennur Road,3 BHK,Puachal,1804,3.0,2.0,102.0
2062,Plot Area,Ready To Move,Magadi Road,2 Bedroom,Bhgarve,1350,1.0,0.0,100.0
6276,Super built-up Area,18-Jul,Hosur Road,3 BHK,PuendWe,1689,3.0,1.0,103.0

In [14]:
df.head()

,area_type,availability,location,size,society,total_sqft,bathrooms,balcony,price(in lakhs)
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [15]:
df["area_type"].unique()

<ArrowStringArray>
['Super built-up  Area', 'Plot  Area', 'Built-up  Area', 'Carpet  Area']
Length: 4, dtype: str

In [16]:
df["availability"].unique()

<ArrowStringArray>
[              '19-Dec',        'Ready To Move',               '18-May',
               '18-Feb',               '18-Nov',               '20-Dec',
               '17-Oct',               '21-Dec',               '19-Sep',
               '20-Sep',               '18-Mar',               '20-Feb',
               '18-Apr',               '20-Aug',               '18-Oct',
               '19-Mar',               '17-Sep',               '18-Dec',
               '17-Aug',               '19-Apr',               '18-Jun',
               '22-Dec',               '22-Jan',               '18-Aug',
               '19-Jan',               '17-Jul',               '18-Jul',
               '21-Jun',               '20-May',               '19-Aug',
               '18-Sep',               '17-May',               '17-Jun',
               '21-May',               '18-Jan',               '20-Mar',
               '17-Dec',               '16-Mar',               '19-Jun',
               '22-Jun',               '19-Jul',               '21-Feb',
 'Immediate Possession',               '19-May',               '17-Nov',
               '20-Oct',               '20-Jun',               '19-Feb',
               '21-Oct',               '21-Jan',               '17-Mar',
               '17-Apr',               '22-May',               '19-Oct',
               '21-Jul',               '21-Nov',               '21-Mar',
               '16-Dec',               '22-Mar',               '20-Jan',
               '21-Sep',               '21-Aug',               '14-Nov',
               '19-Nov',               '15-Nov',               '16-Jul',
               '15-Jun',               '17-Feb',               '20-Nov',
               '20-Jul',               '16-Sep',               '15-Oct',
               '15-Dec',               '16-Oct',               '22-Nov',
               '15-Aug',               '17-Jan',               '16-Nov',
               '20-Apr',               '16-Jan',               '14-Jul']
Length: 81, dtype: str

In [17]:
df["location"].unique()

<ArrowStringArray>
[                       'Electronic City Phase II',
                                'Chikka Tirupathi',
                                     'Uttarahalli',
                              'Lingadheeranahalli',
                                        'Kothanur',
                                      'Whitefield',
                                'Old Airport Road',
                                    'Rajaji Nagar',
                                    'Marathahalli',
                                    'Gandhi Bazar',
 ...
                               'Masjid e Alkareem',
                                   'Sindhi Colony',
                             'Kanakapur main road',
                       'Prasanna layout Herohalli',
                               'Sarvobhogam Nagar',
                                  'Pattegarhpalya',
                                     'Tilak Nagar',
 '12th cross srinivas nagar banshankari 3rd stage',
                               'Havanur extension',
                                   'Abshot Layout']
Length: 1306, dtype: str

In [18]:
df["size"].unique()

<ArrowStringArray>
[     '2 BHK',  '4 Bedroom',      '3 BHK',      '4 BHK',  '6 Bedroom',
  '3 Bedroom',      '1 BHK',       '1 RK',  '1 Bedroom',  '8 Bedroom',
  '2 Bedroom',  '7 Bedroom',      '5 BHK',      '7 BHK',      '6 BHK',
  '5 Bedroom',     '11 BHK',      '9 BHK',          nan,  '9 Bedroom',
     '27 BHK', '10 Bedroom', '11 Bedroom',     '10 BHK',     '19 BHK',
     '16 BHK', '43 Bedroom',     '14 BHK',      '8 BHK', '12 Bedroom',
     '13 BHK', '18 Bedroom']
Length: 32, dtype: str

In [19]:
df["society"].unique()

<ArrowStringArray>
['Coomee ', 'Theanmp',       nan, 'Soiewre', 'DuenaTa', 'Jaades ', 'Brway G',
 'Prrry M', 'Shncyes', 'Skityer',
 ...
 'SRanail', 'Anncyar', 'JJr 2e ', 'Saentpa', 'Emtat H', 'Maa 5a ', 'AeisePV',
 'SJovest', 'ThhtsV ', 'RSntsAp']
Length: 2689, dtype: str

In [20]:
df["bathrooms"].unique()

array([ 2.,  5.,  3.,  4.,  6.,  1.,  9., nan,  8.,  7., 11., 10., 14.,
       27., 12., 16., 40., 15., 13., 18.])

In [21]:
df["balcony"].unique()

array([ 1.,  3., nan,  2.,  0.])

In [22]:
df.isnull().sum()

area_type             0
availability          0
location              1
size                 16
society            5502
total_sqft            0
bathrooms            73
balcony             609
price(in lakhs)       0
dtype: int64

In [23]:
df.drop(columns=['society'], inplace=True)

In [24]:
df.head()

,area_type,availability,location,size,total_sqft,bathrooms,balcony,price(in lakhs)
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,1200,2.0,1.0,51.00

In [25]:
df['bhk'] = df['size'].str.extract(r'(\d+)').astype(float)

In [26]:
df.head()

,area_type,availability,location,size,total_sqft,bathrooms,balcony,price(in lakhs),bhk
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,1056,2.0,1.0,39.07,2.0
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,2600,5.0,3.0,120.00,4.0
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,1440,2.0,3.0,62.00,3.0
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,1521,3.0,1.0,95.00,3.0
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,1200,2.0,1.0,51.00,2.0

In [27]:
df.drop(columns=['size'], inplace=True)

In [28]:
df.head()

,area_type,availability,location,total_sqft,bathrooms,balcony,price(in lakhs),bhk
0,Super built-up Area,19-Dec,Electronic City Phase II,1056,2.0,1.0,39.07,2.0
1,Plot Area,Ready To Move,Chikka Tirupathi,2600,5.0,3.0,120.00,4.0
2,Built-up Area,Ready To Move,Uttarahalli,1440,2.0,3.0,62.00,3.0
3,Super built-up Area,Ready To Move,Lingadheeranahalli,1521,3.0,1.0,95.00,3.0
4,Super built-up Area,Ready To Move,Kothanur,1200,2.0,1.0,51.00,2.0

In [29]:
df['availability'].unique()

<ArrowStringArray>
[              '19-Dec',        'Ready To Move',               '18-May',
               '18-Feb',               '18-Nov',               '20-Dec',
               '17-Oct',               '21-Dec',               '19-Sep',
               '20-Sep',               '18-Mar',               '20-Feb',
               '18-Apr',               '20-Aug',               '18-Oct',
               '19-Mar',               '17-Sep',               '18-Dec',
               '17-Aug',               '19-Apr',               '18-Jun',
               '22-Dec',               '22-Jan',               '18-Aug',
               '19-Jan',               '17-Jul',               '18-Jul',
               '21-Jun',               '20-May',               '19-Aug',
               '18-Sep',               '17-May',               '17-Jun',
               '21-May',               '18-Jan',               '20-Mar',
               '17-Dec',               '16-Mar',               '19-Jun',
               '22-Jun',               '19-Jul',               '21-Feb',
 'Immediate Possession',               '19-May',               '17-Nov',
               '20-Oct',               '20-Jun',               '19-Feb',
               '21-Oct',               '21-Jan',               '17-Mar',
               '17-Apr',               '22-May',               '19-Oct',
               '21-Jul',               '21-Nov',               '21-Mar',
               '16-Dec',               '22-Mar',               '20-Jan',
               '21-Sep',               '21-Aug',               '14-Nov',
               '19-Nov',               '15-Nov',               '16-Jul',
               '15-Jun',               '17-Feb',               '20-Nov',
               '20-Jul',               '16-Sep',               '15-Oct',
               '15-Dec',               '16-Oct',               '22-Nov',
               '15-Aug',               '17-Jan',               '16-Nov',
               '20-Apr',               '16-Jan',               '14-Jul']
Length: 81, dtype: str

In [30]:
df['area_type'].unique()

<ArrowStringArray>
['Super built-up  Area', 'Plot  Area', 'Built-up  Area', 'Carpet  Area']
Length: 4, dtype: str

In [32]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   area_type        13320 non-null  str
 1   availability     13320 non-null  str
 2   location         13319 non-null  str
 3   total_sqft       13320 non-null  str
 4   bathrooms        13247 non-null  float64
 5   balcony          12711 non-null  float64
 6   price(in lakhs)  13320 non-null  float64
 7   bhk              13304 non-null  float64
dtypes: float64(4), str(4)
memory usage: 1.4 MB

In [34]:
df.shape

(13320, 8)